### ISSUE TITLE
[Request] The same for practice.

### ISSUE THREAD

**Issue by oltodosel** [derat/duoleavemealone#1]
Would be nice to have this extension to also skip the need to click 'Continue' button after correct answers during [practice](https://www.duolingo.com/practice).

Edit:
Also those messages like: 'Cool. 5 in a row'.

**Comment by derat** [comment]
Thanks for pointing this out! I didn't realize that Duolingo provided a dedicated "practice" feature; I'd only been using the timed practice that's available when repairing broken skills. I've uploaded version 0.6 to the Chrome Web Store to make the extension also work on https://www.duolingo.com/practice.

I need to think a bit more about how to consistently skip the useless motivational messages. I think that they're correctly detected in the regular skill tree, but not when practicing for some reason. The code to detect them is a huge hack. :-/

**Comment by derat** [comment]
I'm confused, because I've seen the extension fail to skip motivational messages in practice mode (specifically, timed practice) in the past, but I saw it skip a "You are correct" message while I was using https://www.duolingo.com/practice in non-timed mode just now.

Let me know if you find a way to consistently trigger the motivational messages and I'll try to investigate further.

**Comment by oltodosel** [comment]
It seems that those massages are random. I see it as no big deal if once in a while one slips past your scripts.

P.S.
It's unrelated, but from one Duo use to another, you might like this script.
https://greasyfork.org/en/scripts/395615-duolingo-autostart-next-lesson
