### ISSUE TITLE
v 0.10 Sentence ID not found for challenge: - any Practice exercises 

### ISSUE THREAD

**Issue by alexseyk** [derat/duoleavemealone#16]
for any **Practice** type  exercises  via direct link from duome or with duo strength (i.e. non Level 5 practice) -  Sentence ID not found

**Comment by derat** [comment]
I don't have experience with Duo Strength or duome.eu. Can you provide an example of one of the direct links?

Off the top of my head, I'd guess that if you're directly loading a challenge/sentence, then my current technique for getting sentence IDs won't work since it depends on watching for the /sessions URL (e.g. https://www.duolingo.com/2017-06-30/sessions) that Duolingo requests at the start of the session. Maybe there's some other way to get the sentence ID, though.

**Comment by alexseyk** [comment]
Basically they both just provide links to practice exercises https://www.duolingo.com/skill/es/Intro/practice you can add "/practice " to any skill to access it. 
Example above is for Spanish 

It's the same link for Level 5 skill practice / restore, and extension works in such case
