### ISSUE TITLE
Add option for whether correct-answer messages are skipped

### ISSUE THREAD

**Issue by dulakm** [derat/duoleavemealone#24]
Hello,

awesome extension. However, it would be great if the behaviour was configurable. I really do want to skip all of the motivational messages and screens showed after the lesson is complete. However, I don't want to skip the successful messages due to using Duolingo Solution Viewer extension, which I find very useful.

It would be great if we could toggle what to skip in the configuration.

**Comment by derat** [comment]
Sure, that seems reasonable. For now, I'll probably only add an option for whether correct-answer messages are skipped, since I can't think of any reasons why users would want to avoid skipping anything else -- auto-starting timed/untimed practice is already configurable, and all the other screens that get skipped seem devoid of information.

**Comment by derat** [comment]
I've published version 0.20 with the new option.

**Comment by dulakm** [comment]
Awesome, that was really quick. Btw. I agree with your reasoning. Thank you Daniel! 🙏
