### ISSUE TITLE
crown level start page issue 

### ISSUE THREAD

**Issue by alexseyk** [derat/duoleavemealone#29]
FYI: When doing crown exercises  in order, your extension breaks at the next  one. 
You know how it says "Complete [number] challenges to earn the rare Legendary crown!" So the extension breaks (it stops bypassing pages) when doing those challenges consequently.
Exiting crown level and starting it again re-enables extension 

" Continuing after lesson: You've earned 498 XP today" ... keeps running until i press start button (i.e. start next challenge )
<img width="1422" alt="Screen Shot 2021-11-02 at 12 10 40" src="https://user-images.githubusercontent.com/60418150/139790013-5ac87068-01b1-4146-bffc-97f03381146e.png">
<img width="1218" alt="Screen Shot 2021-11-02 at 12 15 25" src="https://user-images.githubusercontent.com/60418150/139790429-82aa5514-20ae-45d8-aa34-b24b635f2cee.png">

**Comment by derat** [comment]
It looks like the URL is e.g. https://www.duolingo.com/skill/es/Intro/1 when you get sent back to the "Prove you're a legend" page after completing a challenge. I think that since the extension doesn't know how to deal with the Plus upsell screen (see https://github.com/derat/duoleavemealone/issues/28#issuecomment-957458933), it keeps clicking the "Start" button.

**Comment by alexseyk** [comment]
FYI On this account   the plus / lingot cost window does not pop-up   
If the "start" button was clicked, it should go to the next challenge

**Comment by derat** [comment]
Do you see the lingot/Plus prompt the first time you start a challenge, while the URL is still https://www.duolingo.com/learn?

After you finish a challenge and the URL starts with `/skill`, I suspect that the extension might be clicking the start button so quickly that the overlay disappears before it can show up.

As a quick workaround, I'm probably just going to make the extension temporarily stop clicking if it's done more than X clicks in the last second, since that's a sign that something's gone wrong.

**Comment by alexseyk** [comment]
> Do you see the lingot/Plus prompt the first time you start a challenge, while the URL is still

Nope i do not :) 

FYI when they charge your for the challenge , they charge you for each one ...  
I saw on the forum the price hiked from 10  to 30.  

PS When  you join a classroom there is no cost for legendary challenges :)

**Comment by derat** [comment]
This should be fixed in 0.25. The extension won't try to skip the screen, but it also won't get stuck. I'll use #28 for discussion of whether this screen should be skipped.
