### ISSUE TITLE
extension  does not work with the new learning path 

### ISSUE THREAD

**Issue by alexseyk** [derat/duoleavemealone#32]
Hi 
please enable your extension to work with re-designed DL inrerface https://blog.duolingo.com/new-duolingo-home-screen-design/ 

Adding yourself to a classroom seems to enable the new design

<img width="1168" alt="Screen Shot 2022-10-14 at 18 35 00" src="https://user-images.githubusercontent.com/60418150/195838525-b05cdc19-74a1-4b66-a8d4-a30f32372179.png">

**Comment by derat** [comment]
Can you tell from the JS console whether the extension is active on the page where you're not seeing the "continue" button be clicked? What's the URL? Hopefully they just introduced a new path that the extension needs to watch for.

When you say "adding yourself to a classroom", do you mean one of the paid classes available at https://classes.duolingo.com/, or something else?

**Comment by alexseyk** [comment]
I dont know how to  tell if the extension is active :(  

URL examples  are as follows:  https://www.duolingo.com/lesson/unit/45/level/6 or https://www.duolingo.com/lesson/unit/51/legendary  or https://www.duolingo.com/lesson/unit/3/test . It seems that  instead of 45 & 6  there can be any number \ integer,  in  the new structure\setup. 

I guess the new path to watch will be https://www.duolingo.com/lesson/unit/* 
Are you watching for https://www.duolingo.com/placement/* too ?

I mean classrooms at school https://schools.duolingo.com/ . When you are in the classroom you get unlimited hearts in the mobile app and the most stable \ old tree structure.  At least it used to be so. 

Wow, classes used to be free :(
 
and the main link to add \ watch for  is https://www.duolingo.com/lesson

**Comment by derat** [comment]
Thanks! Yeah, the extension doesn't currently do anything with `/lesson` URLs. You can see the current URL check here:

https://github.com/derat/duoleavemealone/blob/c6fe01597262b383de3609e3be3521114ac5d852/content.js#L247-L273

If that `if` condition evaluates to `false`, then the extension looks for a "continue" button to click.

I've created a branch with a potential fix at https://github.com/derat/duoleavemealone/tree/lesson. It's possible that more changes will be needed, but if you don't mind testing it, I think that you should be able to do something like the following:

* Download and extract https://github.com/derat/duoleavemealone/archive/refs/heads/lesson.zip.
* Go to chrome://extensions and enable "Developer mode".
* Temporarily disable the copy of duoleavemealone from the Chrome Web Store if installed.
* Click "Load unpacked" and select the directory that was created in the first step.

**Comment by alexseyk** [comment]
Hi
the fix works for \unit\##\lesson|##  type URLs (i.e. for practice after the tile is "golden", but NOT for stories (tiles with a book icon)  )
and for unit\##\test (i.e. for jump ahead) 
and for unit\##\legendary  (i.e. for legendary ) 

however is does not work on just  https://www.duolingo.com/lesson (i.e. for current lesson) :(

Please address that, thanks

**Comment by derat** [comment]
Thanks for testing it out!

I really don't understand Duolingo's URL structure. :-( So, they now display questions at URLs like `https://www.duolingo.com/lesson/unit/45/level/6` (sometimes with additional stuff like `/legendary` or `/test` appended), but also at `https://www.duolingo.com/lesson`? How do you get to the plain `/lesson` URLs?

And just to make sure I understand your last comment, are stories now served at different URLs too? The extension currently looks for `/stories/` in the URL to determine if the user is listening to a story rather than doing the regular question-and-answer format. (Auto-advancing in stories is completely different and uses a different code path in the extension.)

**Comment by alexseyk** [comment]
Hi
I guess your tree  is not updated to new structure yet?

You get plan /lesson URL for the current \ new lesson  

<img width="368" alt="Screen Shot 2022-10-16 at 20 36 11" src="https://user-images.githubusercontent.com/60418150/196038472-4e05e0fb-996e-4cd2-90b0-8ae595916855.png">

Stories are no different than any other lesson 

<img width="325" alt="Screen Shot 2022-10-16 at 20 37 54" src="https://user-images.githubusercontent.com/60418150/196038558-b3173e7c-569c-45b8-81ae-659d4f44ead0.png">
<img width="323" alt="Screen Shot 2022-10-16 at 20 38 01" src="https://user-images.githubusercontent.com/60418150/196038562-b88bc0a8-2e83-46ee-9af1-13f3c2344953.png">
<img width="330" alt="Screen Shot 2022-10-16 at 20 38 09" src="https://user-images.githubusercontent.com/60418150/196038563-04242384-478d-4026-a9ea-24f42a8dc989.png">

https://www.duolingo.com/lesson/unit/77/level/9
https://www.duolingo.com/lesson/unit/77/level/10
https://www.duolingo.com/lesson/unit/77/level/11

<img width="275" alt="Screen Shot 2022-10-16 at 20 42 04" src="https://user-images.githubusercontent.com/60418150/196038722-bb1b40dc-c5ae-4e3f-bc20-4b5f34bf2aac.png">
<img width="533" alt="Screen Shot 2022-10-16 at 20 42 13" src="https://user-images.githubusercontent.com/60418150/196038724-ab4e3038-3a99-4330-ad8b-5dc7878b83c4.png">
<img width="669" alt="Screen Shot 2022-10-16 at 20 43 31" src="https://user-images.githubusercontent.com/60418150/196038774-ef710858-691a-4f52-a666-b4bacc805659.png">

https://www.duolingo.com/lesson/unit/77/legendary


<img width="238" alt="Screen Shot 2022-10-16 at 20 44 20" src="https://user-images.githubusercontent.com/60418150/196038831-4811ece5-ed56-4d17-ab1a-75057a77722c.png">

<img width="939" alt="Screen Shot 2022-10-16 at 20 44 32" src="https://user-images.githubusercontent.com/60418150/196038842-3ece7bed-a653-4a10-acc0-48c4cb15a38b.png">

https://www.duolingo.com/lesson/unit/79/test

**Comment by derat** [comment]
Thanks for all the details. Yeah, my account doesn't have the redesigned tree yet. From https://blog.duolingo.com/new-duolingo-home-screen-design/, it sounds like it's being rolled out to all users on November 1st, so I guess I'll have it in two weeks.

I've pushed another change to the `lesson` branch to also match URLs ending with `/lesson`. If you can confirm that it improves things with the new tree and doesn't seem to break anything that was working before, I'll release a new version of the extension.

I may need to wait until I get the redesigned tree to figure out how to detect stories, since it sounds like they may just appear as regular lessons now.

**Comment by alexseyk** [comment]
Hi Daniel 
I tested new script and can confirm that it works with plain /lesson URLs

thanks
Alex

**Comment by derat** [comment]
Thanks again! I've submitted version 0.30 of the extension to the Chrome Web Store for review.
